### ISSUE TITLE
typo (?) in default settings on OS X

### ISSUE THREAD

**Issue by georgeberry** [quinnj/Sublime-Julia#14]
I've put Sublime-Julia on two different Macs today. It works great on both, BUT I have had to manually make a change to the Users/USERNAME/Library/Application Support/Sublime Text 2/Packages/Sublime-Julia/Config/Julia/Main.sublime-menu file.

Line 34 reads: 
"syntax": "Packages/SublimeJulia/SyntaxJulia.tmLanguage"

Whereas it should read :
"syntax": "Packages/Sublime-Julia/Syntax/Julia.tmLanguage"

Before making this change, when I go to open the REPL I get: "Error loading syntax file..."

After manually making this change, everything works wonderfully.

**Comment by quinnj** [comment]
Thanks for finding this. I believe the error is corrected in the new [Sublime-IJulia](https://github.com/karbarcca/Sublime-IJulia) which supersedes this project. If the issue still persists there, please file another issue.
