### ISSUE TITLE
transpose operator breaks syntax parsing

### ISSUE THREAD

**Issue by bsxfan** [quinnj/Sublime-Julia#3]
The Subllime-Julia syntax parser gets confused by the transpose operator '. See for example the julia source file linalg/factorization.jl

**Comment by quinnj** [comment]
This was actually fixed last week by 4f7360eb583ad6ea3e491acf60c3ba1245c6f229. Are you working on an older Sublime-Julia repo? If so, just navigate to your Sublime-Julia folder/repo and run `git pull` and it should update with changes I've pushed.

**Comment by bsxfan** [comment]
I installed the package yesterday. I did a git pull now anyway and the only file that had changed was the readme.md

**Comment by quinnj** [comment]
Can you post a screenshot of what you're seeing? I looked through
`linalg/factorization.jl` on my system and didn't see any problems

**Comment by bsxfan** [comment]
This line will do it:

```
(\)(A::QR, B::StridedVector) = Triangular(A[:R], 'U')\(A[:Q]'B)[1:size(A, 2)]
```

The last ' makes it believe that anything from B onwards is a text string, so that a large part of the file from there on is just green.

**Comment by bsxfan** [comment]
Could it be that it works differently on windows? Maybe CRLF has something to do wit it?

**Comment by quinnj** [comment]
You're on windows, right? I'm on windows as well and the line of code you posted above works for me. I also know that this works on linux, so I'm not sure what's going on.

**Comment by quinnj** [comment]
Can you make sure that your `Julia.tmLanguage` file (Sublime-Julia -> Syntax -> Julia.tmLanguage) matches [master](https://github.com/karbarcca/Sublime-Julia/blob/master/Syntax/Julia.tmLanguage)?

**Comment by bsxfan** [comment]
My package is fresh. Could it be that yours is lagging? I see you did another commit "Fix a syntax-blocking bug that was reintroduced in the last commit" right after the one that you said had fixed the bug.

**Comment by bsxfan** [comment]
I found this: `Y = A' * B` will not cause the problem, but `Y = A[ii,jj]' * B` does. It is the combination ]' that causes the problem. I saw in the settings files that there are some settings that go on about brackets. Maybe my bracket parsing settings are different from yours?

**Comment by quinnj** [comment]
Hmmmm.........yeah, it might be some kind of other settings thing. I'll see if I can dig around a little more...
