### ISSUE TITLE
Doen't work on Sublime Text 3

### ISSUE THREAD

**Issue by diegozea** [quinnj/Sublime-Julia#5]
Sublime 3 is now available http://www.sublimetext.com/3
This doesn't work on it,

But works fine on Sublime Text 2 :) Nice work!

**Comment by quinnj** [comment]
Yeah, I think I tried it on ST3 once and it didn't work for me either. I believe it's because of SublimeREPL incompatibility which SublimeREPL-Julia is based on. I believe there is work in progress to make it compatible, so maybe I'll take a look again to see if we can get it to work.

**Comment by quinnj** [comment]
Ok, should work on Sublime Text 3 now. I've been running it with ST3 for a week and a half now and worked out a few issues. Closing this for now unless you run into other problems.
