### ISSUE TITLE
Select between two Julia versions

### ISSUE THREAD

**Issue by diegozea** [quinnj/Sublime-Julia#6]
I have Julia 0.1.2 from the Ubuntu's repo, and a 0.2 (master) version.

I setup the PATH to the 0.2 version, but the 0.1.2 is opened every time.

This is my line:

```
"default_extend_env": {"PATH": "/home/dzea/bin/julia-master/usr/bin; {PATH}"},
```

**Comment by quinnj** [comment]
This is probably a `PATH` issue. Is your Julia 0.1.2 version in your path? If it is, will be "found" first when launched.

**Comment by diegozea** [comment]
Yes, installed by the package repository and in the PATH.

**Comment by quinnj** [comment]
In that case, you may just want to switch the two in your `default_extend_env` variable.

`"default_extend_env": {"PATH": "{PATH}; /home/dzea/bin/julia-master/usr/bin"},`

**Comment by diegozea** [comment]
Change the order doesn't help, the installed by the package system looks to have priority always.

**Comment by quinnj** [comment]
This feature is supported in the `Sublime-IJulia` project which supersedes this project. https://github.com/karbarcca/Sublime-IJulia
