### ISSUE TITLE
New REPL shell out syntax for 0.2 doesn't work on SublimeREPL

### ISSUE THREAD

**Issue by diegozea** [quinnj/Sublime-Julia#7]
```
julia> ;ls
# methods for generic function ls
ls(args...) at deprecated.jl:224

julia> versioninfo()
Julia Version 0.2.0-2404.r0abc88fd
Commit 0abc88fd06 2013-07-03 16:42:28
Platform Info:
  System: Linux (x86_64-linux-gnu)
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT)
  LAPACK: libopenblas
  LIBM: libopenlibm
```

**Comment by quinnj** [comment]
This actually isn't a Sublime issue, but a `julia-release-basic` issue. I think @vtjnash or @loladiro will have to comment on whether #[3472](https://github.com/JuliaLang/julia/pull/3472) will be implemented for basic or not.

**Comment by vtjnash** [comment]
#3472 will not be implemented in julia-release-basic. It is strictly a feature of the readline repl.
