### ISSUE TITLE
if statement highlighted as function call

### ISSUE THREAD

**Issue by EsbenPM** [quinnj/Sublime-Julia#9]
If i write "if(1>0)" the if is highlighted as a function, where as "if 1>0" highlights the if differently. 

I assume the intention is for "if" to be highlighted the same way regardless of how it is written.

**Comment by quinnj** [comment]
Sorry for not ever responding to this, but the [Sublime-IJulia](https://github.com/karbarcca/Sublime-IJulia) has been my main focus which supersedes here. I know there have been some syntax file updates, so open an issue on the new repo if you still see the problem.
